import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import "@/lib/mongo";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/lib/context/AuthContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const montoSerat =  Montserrat({
  variable: "--font-montserrat",
  weight: ["400", "700"],
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <head>
       {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"/> */}
    {/* <!-- Font Awesome CSS --> */}
    {/* <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet"></link> */}
      </head> 
      <body
        className={` ${montoSerat.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      
      >
        <AuthProvider>

  {children}
  <Toaster
  toastOptions={{
    style: {
      background: "linear-gradient(to right, #F38DA0, #D946EF)",
      color: "#fff",
      padding: "14px 18px",
      fontWeight: 600,
      borderRadius: "9999px",
      boxShadow: "0 6px 15px rgba(249, 168, 212, 0.35)",
      border: "1px solid rgba(255, 182, 193, 0.4)",
      fontSize: "15px",
    },
    
  }
  
}
  position="top-center"
  
/> 
</AuthProvider>
</body>
    </html>
  );
}
